"""Type stubs for Rust FFI bindings."""
from typing import Any, Dict, Tuple, List

__version__: str

def validate_buffer_size(data: bytes, /) -> None: ...
def validate_utf8_string(data: bytes, /) -> str: ...
def validate_u8_range(value: int, /) -> None: ...

class PyRouteMatcher:
    def add_route(self, pattern: str, method: str, handler_id: str) -> None: ...
    def match_path(self, path: str, method: str) -> Tuple[str, Dict[str, str]]: ...
    def route_count(self) -> int: ...
    def clear(self) -> None: ...

class RequestModule:
    @staticmethod
    def parse_query_params(query: str, /) -> Dict[str, str]: ...
    @staticmethod
    def parse_json(data: bytes, /) -> Any: ...
    @staticmethod
    def parse_form(data: bytes, /) -> Dict[str, str]: ...

class ResponseModule:
    class PyResponseBuilder: ...
    class PyHttpResponse: ...
    @staticmethod
    def serialize_json(data: Dict[str, Any], /) -> bytes: ...
    @staticmethod
    def json_response(status: int, data: Dict[str, Any], /) -> PyHttpResponse: ...
    @staticmethod
    def text_response(status: int, text: str, /) -> PyHttpResponse: ...
    @staticmethod
    def binary_response(status: int, data: bytes, /) -> PyHttpResponse: ...

class ValidationModule:
    class PyBufferValidator: ...
    class PyUtf8Validator: ...
    class PyNumericValidator: ...
    class PySchemaValidator: ...
    @staticmethod
    def u8_validator() -> PyNumericValidator: ...
    @staticmethod
    def i32_validator(min: int, max: int) -> PyNumericValidator: ...
    @staticmethod
    def f64_validator(min: float, max: float) -> PyNumericValidator: ...
    @staticmethod
    def validate_json_schema(data: Dict[str, Any], schema: Dict[str, Any], /) -> Dict[str, Any]: ...

class DependenciesModule:
    class PyDependencyResolver: ...

request: RequestModule
response: ResponseModule
validation: ValidationModule
dependencies: DependenciesModule