"""Type stubs for the Rust FFI library."""

from __future__ import annotations

from typing import Dict, Any, Optional, List, Tuple

# Version information
__version__: str

# Core validation functions
def validate_buffer_size(data: bytes, /) -> None:
    """Validate buffer size against 10MB limit."""
    ...

def validate_utf8_string(data: bytes, /) -> str:
    """Validate and decode UTF-8 byte sequence."""
    ...

def validate_u8_range(value: int, /) -> None:
    """Validate integer is in u8 range (0-255)."""
    ...

# Routing components
class PyRouteMatcher:
    """Rust-backed route matcher for high-performance URL routing."""
    
    id: int
    
    def __init__(self) -> None: ...
    
    def add_route(self, pattern: str, method: str, handler_id: str) -> None:
        """Add a route pattern with method and handler ID."""
        ...
    
    def match_path(self, path: str, method: str) -> Tuple[str, Dict[str, str]]:
        """Match a path and method, returning (handler_id, path_params)."""
        ...
    
    def route_count(self) -> int:
        """Get the number of registered routes."""
        ...
    
    def clear(self) -> None:
        """Clear all registered routes."""
        ...
    
    def __repr__(self) -> str: ...

# Submodules
class RequestModule:
    """Request parsing utilities."""
    
    @staticmethod
    def parse_query_params(query: str, /) -> Dict[str, str]:
        """Parse URL query string into dictionary."""
        ...
    
    @staticmethod
    def parse_json(data: bytes, /) -> Any:
        """Parse JSON data into Python objects."""
        ...
    
    @staticmethod
    def parse_form(data: bytes, /) -> Dict[str, str]:
        """Parse form-encoded data into dictionary."""
        ...

class ResponseModule:
    """Response building utilities."""
    
    class PyResponseBuilder:
        """Builder pattern for HTTP responses."""
        
        id: int
        
        def __init__(self) -> None: ...
        def status(self, code: int) -> None: ...
        def header(self, key: str, value: str) -> None: ...
        def json_body(self, data: Dict[str, Any]) -> None: ...
        def text_body(self, text: str) -> None: ...
        def binary_body(self, data: bytes) -> None: ...
        def build(self) -> 'PyHttpResponse': ...  # noqa: F821
        def __repr__(self) -> str: ...
    
    class PyHttpResponse:
        """HTTP response wrapper."""
        
        id: int
        
        @property
        def status_code(self) -> int: ...
        @property
        def headers(self) -> Dict[str, str]: ...
        def body_bytes(self) -> bytes: ...
        def body_string(self) -> str: ...
        def is_json(self) -> bool: ...
        def is_text(self) -> bool: ...
        def is_binary(self) -> bool: ...
        def is_empty(self) -> bool: ...
        def __repr__(self) -> str: ...
    
    @staticmethod
    def serialize_json(data: Dict[str, Any], /) -> bytes: ...
    @staticmethod
    def json_response(status: int, data: Dict[str, Any], /) -> PyHttpResponse: ...
    @staticmethod
    def text_response(status: int, text: str, /) -> PyHttpResponse: ...
    @staticmethod
    def binary_response(status: int, data: bytes, /) -> PyHttpResponse: ...

class ValidationModule:
    """Advanced validation utilities."""
    
    class PyBufferValidator:
        def __init__(self, max_size: int = 10485760, strict: bool = False) -> None: ...
        def validate(self, data: bytes) -> None: ...
    
    class PyUtf8Validator:
        def __init__(self, allow_empty: bool = True, max_length: Optional[int] = None) -> None: ...
        def validate(self, data: bytes) -> str: ...
    
    class PyNumericValidator:
        def __init__(self, min: float, max: float, type_name: str = "numeric") -> None: ...
        def validate(self, value: float) -> float: ...
        def validate_int(self, value: int) -> int: ...
    
    class PySchemaValidator:
        def __init__(self, strict: bool = False) -> None: ...
        def require_field(self, field: str, field_type: str) -> None: ...
        def optional_field(self, field: str, field_type: str) -> None: ...
        def validate(self, data: Dict[str, Any]) -> Dict[str, Any]: ...
    
    @staticmethod
    def u8_validator() -> PyNumericValidator: ...
    @staticmethod
    def i32_validator(min: int, max: int) -> PyNumericValidator: ...
    @staticmethod
    def f64_validator(min: float, max: float) -> PyNumericValidator: ...
    @staticmethod
    def validate_json_schema(data: Dict[str, Any], schema: Dict[str, Any], /) -> Dict[str, Any]: ...

class DependenciesModule:
    """Dependency injection utilities."""
    
    class PyDependencyResolver:
        id: int
        
        def __init__(self) -> None: ...
        def register(self, key: str, factory: Any, scope: str) -> None: ...
        def resolve(self, key: str) -> Any: ...
        def clear_request_scope(self) -> None: ...
        def get_registered_keys(self) -> List[str]: ...
        def dependency_count(self) -> int: ...
        def __repr__(self) -> str: ...

# Module instances
request: RequestModule
response: ResponseModule
validation: ValidationModule
dependencies: DependenciesModule