"""Type stubs for Rust FFI bindings."""
from typing import Dict, Any, Tuple
def validate_buffer_size(data: bytes, /) -> None: ...
def validate_utf8_string(data: bytes, /) -> str: ...
def validate_u8_range(value: int, /) -> None: ...

class PyRouteMatcher:
    def add_route(self, pattern: str, method: str, handler_id: str) -> None: ...
    def match_path(self, path: str, method: str) -> Tuple[str, Dict[str, str]]: ...
